services:
  - type: web
    name: Zaram-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn myproject.wsgi
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true