# Generated by Django 5.2.1 on 2025-05-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account_owners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=64)),
                ('Email', models.CharField(max_length=64)),
                ('Number', models.IntegerField(max_length=16)),
                ('password', models.CharField()),
            ],
        ),
    ]
