# Generated by Django 5.2.1 on 2025-05-26 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Junction_academy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Free_trials_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=64)),
                ('Email', models.CharField(max_length=64, unique=True)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='account_owners',
            name='Email',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='account_owners',
            name='Number',
            field=models.IntegerField(),
        ),
    ]
